repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 22.3.0  # Use the latest version
    hooks:
      - id: black
        args: ["--line-length=88"]  # Adjust line length as needed
        language_version: python3.7
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # Use the latest version
    hooks:
      - id: flake8
        args: ['--max-line-length=88']
