name: Feature workflow

on:
  push:
    branches:
      - 'feature/*'

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  unittests:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7.16, 3.8.18, 3.9.18, "3.10.13", 3.11.5, 3.12.0]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Google Cloud SDK and Datastore emulator
        run: |
          # Download and install the Google Cloud SDK
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-470.0.0-linux-x86_64.tar.gz
          tar -xzf google-cloud-cli-470.0.0-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh --quiet
          source ./google-cloud-sdk/path.bash.inc
          # Install the Datastore emulator using apt-get
          sudo apt-get update
          sudo apt-get install google-cloud-cli-datastore-emulator

      - name: Run unittests
        uses: ./.github/actions/unittests
        with:
          python-version: ${{ matrix.python-version }}
